version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  checkout_with_git_submodule:
    steps:
      - checkout
      - run: git submodule sync --recursive
      - run: git submodule update --progress --init --recursive

jobs:
  windows_vs2019_x86_32:
    executor: win/default
    steps:
      - checkout_with_git_submodule

workflows:
  version: 2
  build:
    jobs:
      - windows_vs2019_x86_32
