version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  choco_install_cmake:
    steps:
      - run:
          name: install cmake
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'
  checkout_with_git_submodule:
    steps:
      - checkout
      - run:
          name: git submodule
          command: |
            git submodule sync --recursive
            git submodule update --progress --init --recursive
  windows_vs2019_x86_32_devenv_build:
    parameters:
      cmake_build_type:
        type: string
        default: Release
    steps:
      - run:
          name: windows vs2019 x86_32 devenv << parameters.cmake_build_type >> build
          command: |
            mkdir build
            pushd build
            cmake -G "Visual Studio 16" -T v142 -A Win32 ..
            cmake --build . --target install --config << parameters.cmake_build_type >> --clean-first
            popd

jobs:
  windows_vs2019_x86_32_devenv_Release:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_x86_32_devenv_build:
          cmake_build_type: Release
  windows_vs2019_x86_32_devenv_Debug:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_x86_32_devenv_build:
          cmake_build_type: Debug
  windows_vs2019_x86_32_devenv_RelWithDebInfo:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_x86_32_devenv_build:
          cmake_build_type: RelWithDebInfo
  windows_vs2019_x86_32_devenv_MinSizeRel:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_x86_32_devenv_build:
          cmake_build_type: MinSizeRel

  windows_vs2019_x86_32_nmake:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - run:
          name: cmake build Release
          shell: cmd.exe
          command:
            .cicommon\vs2019_command_prompt.bat x86 &&
            .cicommon\cmake_nmake_build.bat

workflows:
  version: 2
  build:
    jobs:
      - windows_vs2019_x86_32_devenv_Release
      - windows_vs2019_x86_32_devenv_Debug
      - windows_vs2019_x86_32_devenv_RelWithDebInfo
      - windows_vs2019_x86_32_devenv_MinSizeRel
      - windows_vs2019_x86_32_nmake
