version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  choco_install_cmake:
    steps:
      - run:
          name: install cmake
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'

  checkout_with_git_submodule:
    steps:
      - checkout
      - run:
          name: git submodule
          command: |
            git submodule sync --recursive
            git submodule update --progress --init --recursive

jobs:
  windows_vs2019_x86_32:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - run:
          name: cmake build
          command: |
            mkdir build
            pushd build
            cmake -G "Visual Studio 16" -T v142 -A Win32 ..
            cmake --build . --target install --config Release --clean-first
            popd

  windows_vs2019_x86_32_nmake:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - run:
          name: cmake build Release
          shell: cmd.exe
          command:
            .cicommon\vs2019_command_prompt.bat x86 &&
            .cicommon\cmake_nmake_build.bat

workflows:
  version: 2
  build:
    jobs:
      - windows_vs2019_x86_32
      - windows_vs2019_x86_32_nmake
