version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  checkout_with_git_submodule:
    steps:
      - checkout
      - run:
          name: git submodule
          command: |
            git submodule sync --recursive
            git submodule update --progress --init --recursive

jobs:
  windows_vs2019_x86_32:
    executor: win/default
    steps:
      - checkout_with_git_submodule
      - run:
          name: install cmake
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'
      - run:
          name: cmake build
          command: |
            mkdir build
            pushd build
            cmake -G "Visual Studio 16" -T v142 -A Win32 ..
            cmake --build . --target install --config Release --clean-first
            popd

  windows_vs2019_x86_32_nmake:
    executor: win/default
    steps:
      - checkout_with_git_submodule
      - run:
          name: install cmake
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'
      - run:
          name: cmake build
          shell: cmd.exe
          command: |
            md build
            pushd build
            call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x86
            cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" ..
            nmake install
            popd

  windows_vs2019_x86_64:
    executor: win/default
    steps:
      - checkout_with_git_submodule
      - run:
          name: install cmake
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'
      - run:
          name: cmake build
          command: |
            mkdir build
            pushd build
            cmake -G "Visual Studio 16" -T v142 -A x64 ..
            cmake --build . --target install --config Release --clean-first
            popd

workflows:
  version: 2
  build:
    jobs:
      - windows_vs2019_x86_32
      - windows_vs2019_x86_32_nmake
      - windows_vs2019_x86_64
