version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  choco_install_cmake:
    steps:
      - run:
          name: install cmake
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'
  checkout_with_git_submodule:
    steps:
      - checkout
      - run:
          name: git submodule
          command: |
            git submodule sync --recursive
            git submodule update --progress --init --recursive

jobs:
  cmake_vs_build:
    executor: win/default
    parameters:
      vs_version:
        type: enum
        enum: [ vs2019 ]
        default: vs2019
      vs_tool:
        type: enum
        enum: [ devenv, nmake ]
        default: devenv
      windows_version:
        type: enum
        enum: [ winxp, win7 ]
        default: winxp
      cmake_options:
        type: string
        default: --
      cmake_build_arch:
        type: enum
        enum: [ x86_32, x86_64 ]
        default: x86_32
      cmake_build_type:
        type: enum
        enum: [ Debug, Release, RelWithDebInfo, MinSizeRel ]
        default: Release
      cmake_build_target:
        type: string
        default: --
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - run:
          name: cmake << parameters.vs_version >> << parameters.vs_tool >> << parameters.windows_version >> << parameters.cmake_build_arch >> << parameters.cmake_build_type >> build << parameters.cmake_build_target >>
          command: |
            .cicommon\cmake_vs_build.bat "<< parameters.vs_version >>" "<< parameters.vs_tool >>" "<< parameters.windows_version >>" "<< parameters.cmake_options >>" "<< parameters.cmake_build_arch >>" "<< parameters.cmake_build_type >>" "<< parameters.cmake_build_target >>"

workflows:
  version: 2
  build:
    jobs:
      - cmake_vs_build:
          name: windows << matrix.vs_version >> << matrix.vs_tool >> << matrix.windows_version >> << matrix.cmake_build_arch >> << matrix.cmake_build_type >> << matrix.cmake_build_target >>
          matrix:
            parameters:
              vs_version: [ vs2019 ]
              vs_tool: [ devenv, nmake ]
              windows_version: [ win7 ]
              cmake_options: [ -- ]
              cmake_build_arch: [ x86_32, x86_64 ]
              cmake_build_type: [ Debug, Release, RelWithDebInfo, MinSizeRel ]
              cmake_build_target: [ install ]
