version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  choco_install_cmake:
    steps:
      - run:
          name: install cmake
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'
  checkout_with_git_submodule:
    steps:
      - checkout
      - run:
          name: git submodule
          command: |
            git submodule sync --recursive
            git submodule update --progress --init --recursive
  windows_vs2019_devenv_x86_32_build:
    parameters:
      cmake_build_type:
        type: string
        # Debug Release RelWithDebInfo MinSizeRel
        default: Release
    steps:
      - run:
          name: windows vs2019 devenv x86_32 << parameters.cmake_build_type >> build
          command: |
            mkdir build
            pushd build
            cmake -G "Visual Studio 16" -T v142 -A Win32 ..
            if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
            cmake --build . --target install --config "<< parameters.cmake_build_type >>" --clean-first
            if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
            popd
  windows_vs2019_devenv_x86_64_build:
    parameters:
      cmake_build_type:
        type: string
        # Debug Release RelWithDebInfo MinSizeRel
        default: Release
    steps:
      - run:
          name: windows vs2019 devenv x86_64 << parameters.cmake_build_type >> build
          command: |
            mkdir build
            pushd build
            cmake -G "Visual Studio 16" -T v142 -A x64 ..
            if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
            cmake --build . --target install --config "<< parameters.cmake_build_type >>" --clean-first
            if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
            popd
  windows_vs2017_vs2019_nmake_build:
    parameters:
      vs_year:
        type: enum
        default: "2019"
        enum: [ "2017", "2019" ]
      vs_arch:
        type: enum
        default: x86
        enum: [ x86, amd64 ]
      cmake_build_type:
        type: enum
        default: Release
        enum: [ Debug, Release, RelWithDebInfo, MinSizeRel ]
    steps:
      - run:
          name: windows vs<< parameters.vs_year >> nmake << parameters.vs_arch >> << parameters.cmake_build_type >> build
          command: |
            $vs_year = "<< parameters.vs_year >>"
            $vs_arch = "<< parameters.vs_arch >>"
            if (($vs_year -ne "2019") -and ($vs_year -ne "2017")) {
                $vs_year = "2019"
            }
            pushd HKLM:\SOFTWARE\WOW6432Node\Microsoft
            ls VisualStudio_* | foreach {
                $vs_id = $_.Name.Substring("HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\VisualStudio_".Length)
                $app_name = gpv "HKLM:\SOFTWARE\WOW6432Node\Microsoft\VisualStudio_$($vs_id)\Capabilities" ApplicationName
                if ($app_name -eq "Microsoft Visual Studio $($vs_year)") {
                    $install_location = gpv "HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\$($vs_id)" InstallLocation
                    if ($install_location -ne "") {
                        $env:VCVARSALL = "$($install_location)\VC\Auxiliary\Build\vcvarsall.bat"
                    }
                }
            }
            popd
            cmd /c """%VCVARSALL%"" $($vs_arch) & set" | foreach {
                if ($_ -match "=") {
                    $v = $_.Split("=")
                    si -Path "env:\$($v[0])" -Value "$($v[1])" -Force
                }
            }
            mkdir build
            pushd build
            cmake -DCMAKE_BUILD_TYPE=<< parameters.cmake_build_type >> -G "NMake Makefiles" ..
            if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
            cmake --build . --target install --config "<< parameters.cmake_build_type >>" --clean-first
            if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
            popd
  windows_vs2019_nmake_x86_32_build:
    parameters:
      cmake_build_type:
        type: string
        # Debug Release RelWithDebInfo MinSizeRel
        default: Release
    steps:
      - run:
          name: windows vs2019 nmake x86_32 << parameters.cmake_build_type >> build
          shell: cmd.exe
          command:
            .cicommon\vs2019_command_prompt.bat x86 &&
            .cicommon\cmake_nmake_build.bat "<< parameters.cmake_build_type >>"
  windows_vs2019_nmake_x86_64_build:
    parameters:
      cmake_build_type:
        type: string
        # Debug Release RelWithDebInfo MinSizeRel
        default: Release
    steps:
      - run:
          name: windows vs2019 nmake x86_64 << parameters.cmake_build_type >> build
          shell: cmd.exe
          command:
            .cicommon\vs2019_command_prompt.bat amd64 &&
            .cicommon\cmake_nmake_build.bat "<< parameters.cmake_build_type >>"

jobs:
  windows_vs2019_devenv_x86_32_Release:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_devenv_x86_32_build:
          cmake_build_type: Release
  windows_vs2019_devenv_x86_32_Debug:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_devenv_x86_32_build:
          cmake_build_type: Debug
  windows_vs2019_devenv_x86_32_RelWithDebInfo:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_devenv_x86_32_build:
          cmake_build_type: RelWithDebInfo
  windows_vs2019_devenv_x86_32_MinSizeRel:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_devenv_x86_32_build:
          cmake_build_type: MinSizeRel
  windows_vs2019_devenv_x86_64_Release:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_devenv_x86_64_build:
          cmake_build_type: Release
  windows_vs2019_devenv_x86_64_Debug:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_devenv_x86_64_build:
          cmake_build_type: Debug
  windows_vs2019_devenv_x86_64_RelWithDebInfo:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_devenv_x86_64_build:
          cmake_build_type: RelWithDebInfo
  windows_vs2019_devenv_x86_64_MinSizeRel:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_devenv_x86_64_build:
          cmake_build_type: MinSizeRel
  windows_vs2019_nmake_x86_32_Release:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_nmake_x86_32_build:
          cmake_build_type: Release
  windows_vs2019_nmake_x86_32_Debug:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2017_vs2019_nmake_build:
          vs_year: 2019
          vs_arch: x86
          cmake_build_type: Debug
  windows_vs2019_nmake_x86_32_RelWithDebInfo:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_nmake_x86_32_build:
          cmake_build_type: RelWithDebInfo
  windows_vs2019_nmake_x86_32_MinSizeRel:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_nmake_x86_32_build:
          cmake_build_type: MinSizeRel
  windows_vs2019_nmake_x86_64_Release:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_nmake_x86_64_build:
          cmake_build_type: Release
  windows_vs2019_nmake_x86_64_Debug:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_nmake_x86_64_build:
          cmake_build_type: Debug
  windows_vs2019_nmake_x86_64_RelWithDebInfo:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_nmake_x86_64_build:
          cmake_build_type: RelWithDebInfo
  windows_vs2019_nmake_x86_64_MinSizeRel:
    executor: win/default
    steps:
      - choco_install_cmake
      - checkout_with_git_submodule
      - windows_vs2019_nmake_x86_64_build:
          cmake_build_type: MinSizeRel

workflows:
  version: 2
  build:
    jobs:
      #- windows_vs2019_devenv_x86_32_Release
      #- windows_vs2019_devenv_x86_32_Debug
      #- windows_vs2019_devenv_x86_32_RelWithDebInfo
      #- windows_vs2019_devenv_x86_32_MinSizeRel
      #- windows_vs2019_devenv_x86_64_Release
      #- windows_vs2019_devenv_x86_64_Debug
      #- windows_vs2019_devenv_x86_64_RelWithDebInfo
      #- windows_vs2019_devenv_x86_64_MinSizeRel
      #- windows_vs2019_nmake_x86_32_Release
      - windows_vs2019_nmake_x86_32_Debug
      #- windows_vs2019_nmake_x86_32_RelWithDebInfo
      #- windows_vs2019_nmake_x86_32_MinSizeRel
      #- windows_vs2019_nmake_x86_64_Release
      #- windows_vs2019_nmake_x86_64_Debug
      #- windows_vs2019_nmake_x86_64_RelWithDebInfo
      #- windows_vs2019_nmake_x86_64_MinSizeRel
