version: 2.1

orbs:
  win: circleci/windows@2.4.0

commands:
  checkout_with_git_submodule:
    steps:
      - checkout
      - run:
          name: git submodule
          command: |
            git submodule sync --recursive
            git submodule update --progress --init --recursive

jobs:
  windows_vs2019_x86_32:
    executor: win/default
    steps:
      - checkout_with_git_submodule
      - run:
          name: install cmake
          command: |
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=User'
      - run:
          name: get cmake version
          command: |
            cmake --version

workflows:
  version: 2
  build:
    jobs:
      - windows_vs2019_x86_32
